---
language: node_js
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm config set spin false
install:
  - npm i
script:
  - npm test
after_success:
  - npm run semantic-release