---
language: node_js
node_js:
  - "6.9.1"
addons:
  apt:
    packages:
    - nginx
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm config set spin false
  - nginx
install:
  - npm i
  - nginx -t
script:
  - npm test
after_success:
  - npm run semantic-release